[package]
name = "wasm-rust"
version = "0.1.0"
authors = ["Justis <justis710@gmail.com>"]
edition = "2018"

[lib]
name = "wasm_rust_example"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.68"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-02", "--enable-mutable-globals"]
